### ISSUE TITLE
Сохранение результатов расчетов в формате CSV

### ISSUE THREAD

**Issue by eugesh** [manichev/pa10project#10]
Реализовать загрузку и сохранение, сделать меню выбора формата - .rez, .csv, .pa10.

**Comment by eugesh** [comment]
Результаты сохраняются в поддиректорию `output` в формате `CSV` с расширением `.rez` для уравнений, заданных в текстовом виде, и `.pa10` - для схем.  
Есть баг - в заголовке не отображаются имена производных, хотя в столбцах данные есть.  
Еще мне кажется было бы удобнее сохранять результаты схем также с именем схемы и другим расширением (сейчас всегда одно имя - `scheme.pa10`). Или `scheme_имя схемы.rez`, т.к. формат файлов одинаковый.

**Comment by eugesh** [comment]
Я изменил заголовок и заменил разделитель - теперь это настоящий CSV.

**Comment by manichev** [comment]
согласен
С уважением.
С наилучшими пожеланиями,

Владимир Борисович Маничев (Vladimir Manichev)
к.т.н., доцент,
105005, Москва, МГТУ им.Н.Э.Баумана, кафедра РК-6 (САПР),
https://rk6.bmstu.ru/index.php?option=com_content&view=article&id=44&catid=10&Itemid=128
<http://www.bmstu.ru/ps/~manichev/>





вт, 19 апр. 2022 г. в 09:23, Evgeny Shtanov ***@***.***>:

**Comment by manichev** [comment]
CSV - Comma Separated Value?

С уважением.
С наилучшими пожеланиями,

Владимир Борисович Маничев (Vladimir Manichev)
к.т.н., доцент,
105005, Москва, МГТУ им.Н.Э.Баумана, кафедра РК-6 (САПР),
https://rk6.bmstu.ru/index.php?option=com_content&view=article&id=44&catid=10&Itemid=128
<http://www.bmstu.ru/ps/~manichev/>





вт, 19 апр. 2022 г. в 12:57, Evgeny Shtanov ***@***.***>:
