### ISSUE TITLE
Указание пути к MinGW в настройках

### ISSUE THREAD

**Issue by eugesh** [manichev/pa10project#11]
В кросс-платформенной версии будет удобно указывать путь к имеющемуся на компьютере MinGW, например поставляемому вместе с Qt, чем копировать дистрибутив вместе с проектом. То же самое касается QWT (или QCustomPlot).

**Comment by manichev** [comment]
согласен

сб, 4 сент. 2021 г., 17:20 Evgeny Shtanov ***@***.***>:

**Comment by eugesh** [comment]
Вынес в настройки в схематическом и текстовом режимах.

**Comment by manichev** [comment]
ок


С уважением.
С наилучшими пожеланиями,

Владимир Борисович Маничев (Vladimir Manichev)
к.т.н., доцент,
105005, Москва, МГТУ им.Н.Э.Баумана, кафедра РК-6 (САПР),
https://rk6.bmstu.ru/index.php?option=com_content&view=article&id=44&catid=10&Itemid=128




вс, 9 янв. 2022 г. в 13:39, Evgeny Shtanov ***@***.***>:

**Comment by manichev** [comment]
ок


С уважением.
С наилучшими пожеланиями,

Владимир Борисович Маничев (Vladimir Manichev)
к.т.н., доцент,
105005, Москва, МГТУ им.Н.Э.Баумана, кафедра РК-6 (САПР),
https://rk6.bmstu.ru/index.php?option=com_content&view=article&id=44&catid=10&Itemid=128
<http://www.bmstu.ru/ps/~manichev/>





вс, 9 янв. 2022 г. в 13:39, Evgeny Shtanov ***@***.***>:
