### ISSUE TITLE
Восстановление электрических соединений по загруженным из файла компонентам

### ISSUE THREAD

**Issue by eugesh** [manichev/pa10project#13]
Нашел проект на Гитхабе - [симулятор сетей Петри](https://github.com/eugesh/petri-net-simulator). В нем реализована эта функция, могу по подобию сделать.

**Comment by manichev** [comment]
хорошо


С уважением.
С наилучшими пожеланиями,

Владимир Борисович Маничев (Vladimir Manichev)
к.т.н., доцент,
105005, Москва, МГТУ им.Н.Э.Баумана, кафедра РК-6 (САПР),
https://rk6.bmstu.ru/index.php?option=com_content&view=article&id=44&catid=10&Itemid=128
<http://www.bmstu.ru/ps/~manichev/>





пн, 13 дек. 2021 г. в 13:41, Evgeny Shtanov ***@***.***>:

**Comment by eugesh** [comment]
Проблема актуальна при сохранении в netkist, т.к. в нем не сохраняются координаты связей. Но пока должно хватать внутреннего формата #9.
