### ISSUE TITLE
Автоматическое копирование ресурсов в директорию сборки проекта

### ISSUE THREAD

**Issue by eugesh** [manichev/pa10project#14]
Некоторые иконки не подгружаются, приходится копировать вручную.

**Comment by manichev** [comment]
понятно


С уважением.
С наилучшими пожеланиями,

Владимир Борисович Маничев (Vladimir Manichev)
к.т.н., доцент,
105005, Москва, МГТУ им.Н.Э.Баумана, кафедра РК-6 (САПР),
https://rk6.bmstu.ru/index.php?option=com_content&view=article&id=44&catid=10&Itemid=128
<http://www.bmstu.ru/ps/~manichev/>





пн, 13 дек. 2021 г. в 13:43, Evgeny Shtanov ***@***.***>:

**Comment by eugesh** [comment]
Проблема решилась указанием путей к иконкам в файле ресурсов и заданием соответствия в ui форме:
7493f30d1988b6b9c8ba31f7686748574ec01f22

**Comment by manichev** [comment]
ок


С уважением.
С наилучшими пожеланиями,

Владимир Борисович Маничев (Vladimir Manichev)
к.т.н., доцент,
105005, Москва, МГТУ им.Н.Э.Баумана, кафедра РК-6 (САПР),
https://rk6.bmstu.ru/index.php?option=com_content&view=article&id=44&catid=10&Itemid=128
<http://www.bmstu.ru/ps/~manichev/>





<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

вс, 9 янв. 2022 г. в 13:41, Evgeny Shtanov ***@***.***>:

**Comment by manichev** [comment]
ок


С уважением.
С наилучшими пожеланиями,

Владимир Борисович Маничев (Vladimir Manichev)
к.т.н., доцент,
105005, Москва, МГТУ им.Н.Э.Баумана, кафедра РК-6 (САПР),
https://rk6.bmstu.ru/index.php?option=com_content&view=article&id=44&catid=10&Itemid=128
<http://www.bmstu.ru/ps/~manichev/>





вс, 9 янв. 2022 г. в 13:41, Evgeny Shtanov ***@***.***>:
