### ISSUE TITLE
Баг: некорректно отображаются буквы кириллицы в настройках задания пути к g++

### ISSUE THREAD

**Issue by eugesh** [manichev/pa10project#29]

**Comment by eugesh** [comment]
У меня не проявляется. В других местах все нормально я кириллицей?

**Comment by eugesh** [comment]
У меня не проявляется. В других местах все нормально я кириллицей?

**Comment by manichev** [comment]
да, все нормально


С уважением.
С наилучшими пожеланиями,

Владимир Борисович Маничев (Vladimir Manichev)
к.т.н., доцент,
105005, Москва, МГТУ им.Н.Э.Баумана, кафедра РК-6 (САПР),
https://rk6.bmstu.ru/index.php?option=com_content&view=article&id=44&catid=10&Itemid=128
<http://www.bmstu.ru/ps/~manichev/>





чт, 7 апр. 2022 г. в 22:36, Evgeny Shtanov ***@***.***>:
