### ISSUE TITLE
Неактивен редактор схем в проекте, собранном под Ubuntu

### ISSUE THREAD

**Issue by eugesh** [manichev/pa10project#3]

**Comment by manichev** [comment]
сейчас актуально собрать па10 мини на питоне

пн, 16 авг. 2021 г., 07:34 Evgeny Shtanov ***@***.***>:

**Comment by manichev** [comment]
тестовые уравнения в текстовом формате решаются у тебя?

пн, 16 авг. 2021 г., 07:34 Evgeny Shtanov ***@***.***>:

**Comment by eugesh** [comment]
Я выяснил, в чем проблема - под Linux сетка отображается слишком часто - условие:
```
            hoveredItem = scene()->itemAt(mapToScene(event->pos()), QTransform());  
            if(hoveredItem != nullptr)
```
выполняется всегда - потому что сетка тоже `QGraphicsItem`, и курсор всегда на нее попадает.
Я исправил так, чтобы вызывалось меню добавления элементов, но пока не сделал более приемлемый вид сетки.

**Comment by manichev** [comment]
ок

С уважением.
С наилучшими пожеланиями,

Владимир Борисович Маничев (Vladimir Manichev)
к.т.н., доцент,
105005, Москва, МГТУ им.Н.Э.Баумана, кафедра РК-6 (САПР),
https://rk6.bmstu.ru/index.php?option=com_content&view=article&id=44&catid=10&Itemid=128
<http://www.bmstu.ru/ps/~manichev/>





чт, 19 авг. 2021 г. в 23:53, Evgeny Shtanov ***@***.***>:

**Comment by manichev** [comment]
попробуй lc.txt идеальный колебательный контур, чистая синусоида должна быть


С уважением.
С наилучшими пожеланиями,

Владимир Борисович Маничев (Vladimir Manichev)
к.т.н., доцент,
105005, Москва, МГТУ им.Н.Э.Баумана, кафедра РК-6 (САПР),
https://rk6.bmstu.ru/index.php?option=com_content&view=article&id=44&catid=10&Itemid=128




чт, 19 авг. 2021 г. в 23:53, Evgeny Shtanov ***@***.***>:

**Comment by eugesh** [comment]
![image](https://user-images.githubusercontent.com/19983888/130206189-e38cd9e4-167a-471b-a89b-772b1cc3f5ab.png)

**Comment by manichev** [comment]
это вроде правильно, это текст уравнений?

С уважением.
С наилучшими пожеланиями,

Владимир Борисович Маничев (Vladimir Manichev)
к.т.н., доцент,
105005, Москва, МГТУ им.Н.Э.Баумана, кафедра РК-6 (САПР),
https://rk6.bmstu.ru/index.php?option=com_content&view=article&id=44&catid=10&Itemid=128
<http://www.bmstu.ru/ps/~manichev/>





пт, 20 авг. 2021 г. в 11:41, Evgeny Shtanov ***@***.***>:

**Comment by eugesh** [comment]
Это графики, полученные после решения  `lc.txt`.

**Comment by eugesh** [comment]
Сетку тоже поправил:  
![image](https://user-images.githubusercontent.com/19983888/130229408-8306fa3e-d9fd-436e-b3e5-0cd67ffd1394.png)

**Comment by manichev** [comment]
С уважением.
С наилучшими пожеланиями,

Владимир Борисович Маничев (Vladimir Manichev)
к.т.н., доцент,
105005, Москва, МГТУ им.Н.Э.Баумана, кафедра РК-6 (САПР),
https://rk6.bmstu.ru/index.php?option=com_content&view=article&id=44&catid=10&Itemid=128
<http://www.bmstu.ru/ps/~manichev/>

а собрать эту схему получится?



пт, 20 авг. 2021 г. в 14:51, Evgeny Shtanov ***@***.***>:

**Comment by manichev** [comment]
отлично,  пришли, пожалуйста, сборку и инструкцию по сборке, попробую у
себя под убунту собрать


С уважением.
С наилучшими пожеланиями,

Владимир Борисович Маничев (Vladimir Manichev)
к.т.н., доцент,
105005, Москва, МГТУ им.Н.Э.Баумана, кафедра РК-6 (САПР),
https://rk6.bmstu.ru/index.php?option=com_content&view=article&id=44&catid=10&Itemid=128
<http://www.bmstu.ru/ps/~manichev/>





пт, 20 авг. 2021 г. в 14:55, Evgeny Shtanov ***@***.***>:

**Comment by eugesh** [comment]
Я все выложил, ветвь - `cpp_linux_build`. 
Что-то не так с парсером. На входе уравнение Дуффинга из sources/tests:
```
k1:=0.5
k2:=0.25
k3:=0.3
kt:=1.0
x1'-x2=0
x2'-k1*x1+k2*x2+k1*x1*x1*x1-k3*cos(kt*t)=0
x1==0
x2==0
```
На выходе:
```
void fcttask(double z[], double px[], double f[], double rj1[], double rj2[], int n, int m, double t, double h, int ncon, int *nbad, int ip[])
{
	f[1] = px[1]-z[2];
	rj1[1*n+1] = 1;
	f[2] = px[2];
	rj1[2*n+2] = 1;
}
```

**Comment by manichev** [comment]
fct у дуффинга другое, см. описание manzhuk


С уважением.
С наилучшими пожеланиями,

Владимир Борисович Маничев (Vladimir Manichev)
к.т.н., доцент,
105005, Москва, МГТУ им.Н.Э.Баумана, кафедра РК-6 (САПР),
https://rk6.bmstu.ru/index.php?option=com_content&view=article&id=44&catid=10&Itemid=128
<http://www.bmstu.ru/ps/~manichev/>





пт, 20 авг. 2021 г. в 18:38, Evgeny Shtanov ***@***.***>:

**Comment by eugesh** [comment]
Где описание, не подскажите? Именно этот fcttask обновлялся при запуске решателя.

**Comment by manichev** [comment]
fct для всех тестов есть в описании манжука
https://yadi.sk/i/urvrhIZ__LfSFA

С уважением.
С наилучшими пожеланиями,

Владимир Борисович Маничев (Vladimir Manichev)
к.т.н., доцент,
105005, Москва, МГТУ им.Н.Э.Баумана, кафедра РК-6 (САПР),
https://rk6.bmstu.ru/index.php?option=com_content&view=article&id=44&catid=10&Itemid=128



пт, 20 авг. 2021 г. в 22:34, Evgeny Shtanov ***@***.***>:

**Comment by eugesh** [comment]
Я о том и говорю, что `fct` был сгенерирован неверно. Разве можно в `ПА10` подменять `fct` - он генерируется автоматически.

**Comment by manichev** [comment]
fcttask генерируется по текстовому описанию систем ОДУ-ДАУ


С уважением.
С наилучшими пожеланиями,

Владимир Борисович Маничев (Vladimir Manichev)
к.т.н., доцент,
105005, Москва, МГТУ им.Н.Э.Баумана, кафедра РК-6 (САПР),
https://rk6.bmstu.ru/index.php?option=com_content&view=article&id=44&catid=10&Itemid=128
<http://www.bmstu.ru/ps/~manichev/>





сб, 21 авг. 2021 г. в 12:01, Evgeny Shtanov ***@***.***>:

**Comment by manichev** [comment]
почитай внимательно описание манжука с тестами

сб, 21 авг. 2021 г., 12:01 Evgeny Shtanov ***@***.***>:

**Comment by manichev** [comment]
па10 мини по математической записи уравнений генерирует функции fct  и out

сб, 21 авг. 2021 г., 12:01 Evgeny Shtanov ***@***.***>:

**Comment by eugesh** [comment]
Я о том и говорю, что в версии под Linux fct не всегда генерируется корректно.

**Comment by manichev** [comment]
Женя, разработай ПА10 мини на Питоне, ТЗ по ссылке, если что будет неясно,
спрашивай
https://yadi.sk/d/X1mNAyC2YKAvAw


С уважением.
С наилучшими пожеланиями,

Владимир Борисович Маничев (Vladimir Manichev)
к.т.н., доцент,
105005, Москва, МГТУ им.Н.Э.Баумана, кафедра РК-6 (САПР),
https://rk6.bmstu.ru/index.php?option=com_content&view=article&id=44&catid=10&Itemid=128
<http://www.bmstu.ru/ps/~manichev/>





пн, 23 авг. 2021 г. в 08:11, Evgeny Shtanov ***@***.***>:
