### ISSUE TITLE
Починить запись в результатов в поддиректорию output

### ISSUE THREAD

**Issue by eugesh** [manichev/pa10project#8]
Сделать так, чтобы результаты вычислений ПА10-мини можно было просматривать во "вьювере".

**Comment by manichev** [comment]
ок, но должно быть 4 периода за время расчёта 4 мю

ср, 1 сент. 2021 г., 23:40 Evgeny Shtanov ***@***.***>:

**Comment by manichev** [comment]
программа графиков действительно не отлажена

ср, 1 сент. 2021 г., 23:40 Evgeny Shtanov ***@***.***>:

**Comment by eugesh** [comment]
Я указывал большее время расчета - получал больше периодов.

**Comment by manichev** [comment]
значит все решает правильно

чт, 2 сент. 2021 г., 11:53 Evgeny Shtanov ***@***.***>:

**Comment by manichev** [comment]
надо выдать результаты в числовои виде и графически?

чт, 2 сент. 2021 г., 11:53 Evgeny Shtanov ***@***.***>:

**Comment by eugesh** [comment]
Если есть возможность найти набор тестов для сравнения текстового и графического ввода - было бы очень удобно. Пока я сделал вывод в текстовый файл для открытия во вьювере. Графики собираюсь переделать. ПА-10 позволяет использовать библиотеки с GPL лицензией?

**Comment by manichev** [comment]
для любого графического ввода формируется и сохраняется текстовый файл,
графические схемы не сохраняются, это желательно добавить, с GPL конечно
можно использовать


С уважением.
С наилучшими пожеланиями,

Владимир Борисович Маничев (Vladimir Manichev)
к.т.н., доцент,
105005, Москва, МГТУ им.Н.Э.Баумана, кафедра РК-6 (САПР),
https://rk6.bmstu.ru/index.php?option=com_content&view=article&id=44&catid=10&Itemid=128
<http://www.bmstu.ru/ps/~manichev/>





чт, 2 сент. 2021 г. в 13:21, Evgeny Shtanov ***@***.***>:

**Comment by manichev** [comment]
Женя, у тебя электрические схемы собираются?


С уважением.
С наилучшими пожеланиями,

Владимир Борисович Маничев (Vladimir Manichev)
к.т.н., доцент,
105005, Москва, МГТУ им.Н.Э.Баумана, кафедра РК-6 (САПР),
https://rk6.bmstu.ru/index.php?option=com_content&view=article&id=44&catid=10&Itemid=128
<http://www.bmstu.ru/ps/~manichev/>





чт, 2 сент. 2021 г. в 13:21, Evgeny Shtanov ***@***.***>:

**Comment by eugesh** [comment]
Я закрыл эту задачу коммитом d7d3980e78569e15e2d49f7303d6cae467398033.
Может быть перевести все изменения на ветку main? Я проверял под Ubuntu и Windows - в Qt Creator'e и Visual Studio 2017.

**Comment by manichev** [comment]
хорошо

пт, 3 сент. 2021 г., 21:44 Evgeny Shtanov ***@***.***>:
