### ISSUE TITLE
Сохранение электрических схем в файл

### ISSUE THREAD

**Issue by eugesh** [manichev/pa10project#9]
Продумать формат, сделать загрузку и сохранение в файл.

**Comment by eugesh** [comment]
Я нашел открытый проект - [netlistsvg](https://github.com/nturley/netlistsvg), в нем `netlist` считывается в формате `json`. Часто ли используется `json` для сохранения электрических схем?

**Comment by eugesh** [comment]
Я установил `OpenModelica` последней версии под Ubuntu, но даже не нашел в `OMEdit` библиотеки электрических схем. Сейчас пробую под Windows поставить.

**Comment by eugesh** [comment]
Под Windows я запустил симуляцию электрических схем в OpenModelica. Но сохранение идет в специфичный формат, не классический netlist. И сохраняются координаты элементов на сцене.

**Comment by manichev** [comment]
они используют кутэ


С уважением.
С наилучшими пожеланиями,

Владимир Борисович Маничев (Vladimir Manichev)
к.т.н., доцент,
105005, Москва, МГТУ им.Н.Э.Баумана, кафедра РК-6 (САПР),
https://rk6.bmstu.ru/index.php?option=com_content&view=article&id=44&catid=10&Itemid=128
<http://www.bmstu.ru/ps/~manichev/>





сб, 4 сент. 2021 г. в 13:44, Evgeny Shtanov ***@***.***>:

**Comment by manichev** [comment]
да, часто


С уважением.
С наилучшими пожеланиями,

Владимир Борисович Маничев (Vladimir Manichev)
к.т.н., доцент,
105005, Москва, МГТУ им.Н.Э.Баумана, кафедра РК-6 (САПР),
https://rk6.bmstu.ru/index.php?option=com_content&view=article&id=44&catid=10&Itemid=128
<http://www.bmstu.ru/ps/~manichev/>





сб, 4 сент. 2021 г. в 10:07, Evgeny Shtanov ***@***.***>:

**Comment by eugesh** [comment]
Мне вариант с JSON нравится. Сериализация есть не для всех классов, к тому же QGraphicsItem - не наследует QObject.

**Comment by manichev** [comment]
понятно, согласен

пн, 6 сент. 2021 г., 09:06 Evgeny Shtanov ***@***.***>:

**Comment by eugesh** [comment]
На данный момент сделал сохранение и загрузку элементов цепи в JSON, без соединений.

**Comment by manichev** [comment]
отлично, формат выбрал правильно

вт, 7 сент. 2021 г., 16:10 Evgeny Shtanov ***@***.***>:

**Comment by eugesh** [comment]
Добавил сохранение/загрузку узлов (node). Со связями чуть сложнее при загрузке - netlist не сохраняет координаты точек соединений.

**Comment by manichev** [comment]
понятно

сб, 18 сент. 2021 г., 05:03 Evgeny Shtanov ***@***.***>:

**Comment by manichev** [comment]
а схему в формате JSON получается сохранять?

сб, 18 сент. 2021 г., 05:03 Evgeny Shtanov ***@***.***>:

**Comment by manichev** [comment]
PS
:Женя, напиши, пожалуйста, пособие по сериализации на этом примере для
студентов


С уважением.
С наилучшими пожеланиями,

Владимир Борисович Маничев (Vladimir Manichev)
к.т.н., доцент,
105005, Москва, МГТУ им.Н.Э.Баумана, кафедра РК-6 (САПР),
https://rk6.bmstu.ru/index.php?option=com_content&view=article&id=44&catid=10&Itemid=128
<http://www.bmstu.ru/ps/~manichev/>





сб, 18 сент. 2021 г. в 05:03, Evgeny Shtanov ***@***.***>:

**Comment by eugesh** [comment]
JSON. Вопрос скорее как по графу связей восстанавливать геометрию схемы.
По сериализации есть примеры (Qt5\Examples\Qt-5.14.1\corelib\serialization) в Qt. Есть много статей в интернете, но я делаю по примеру.

**Comment by manichev** [comment]
ok

пн, 20 сент. 2021 г., 16:08 Evgeny Shtanov ***@***.***>:

**Comment by manichev** [comment]
PS
по сериализации какой пример?



С уважением.
С наилучшими пожеланиями,

Владимир Борисович Маничев (Vladimir Manichev)
к.т.н., доцент,
105005, Москва, МГТУ им.Н.Э.Баумана, кафедра РК-6 (САПР),
https://rk6.bmstu.ru/index.php?option=com_content&view=article&id=44&catid=10&Itemid=128
<http://www.bmstu.ru/ps/~manichev/>





пн, 20 сент. 2021 г. в 16:08, Evgeny Shtanov ***@***.***>:

**Comment by eugesh** [comment]
Я использовал [savegame](https://doc.qt.io/qt-5/qtcore-serialization-savegame-example.html)

**Comment by manichev** [comment]
понятно


С уважением.
С наилучшими пожеланиями,

Владимир Борисович Маничев (Vladimir Manichev)
к.т.н., доцент,
105005, Москва, МГТУ им.Н.Э.Баумана, кафедра РК-6 (САПР),
https://rk6.bmstu.ru/index.php?option=com_content&view=article&id=44&catid=10&Itemid=128
<http://www.bmstu.ru/ps/~manichev/>





вт, 21 сент. 2021 г. в 00:59, Evgeny Shtanov ***@***.***>:

**Comment by manichev** [comment]
спасибо, понятно

пт, 29 окт. 2021 г., 07:02 Evgeny Shtanov ***@***.***>:

**Comment by eugesh** [comment]
Я сделал сохранение и загрузку схем во внутренний формат, продиктованный принципом соединения элементов: в текущей версии связывающие контакты не являются отдельными сущностями, а входят в состав элементов.
Могу сделать релиз, буду разбираться с проблемой трансляции схемы в дифф. уравнения. Задачу закрою, т.к. сохранение в netlist и восстановление по нему связей считаю отдельной проблемой.

**Comment by manichev** [comment]
ок

ср, 5 янв. 2022 г., 19:27 Evgeny Shtanov ***@***.***>:

**Comment by eugesh** [comment]
Вам надо видео на youtube выложить для "чайников" с объяснением работы метода. Я регулярно смотрю разные видео (например, ["диодов нет"](https://www.youtube.com/watch?v=CVb7OWoLhWk)).  
Еще были бы очень полезны примеры "электрическая схема - уравнения - fcttask". Как минимум для отладки парсера.

**Comment by manichev** [comment]
согласен, надо подумать


С уважением.
С наилучшими пожеланиями,

Владимир Борисович Маничев (Vladimir Manichev)
к.т.н., доцент,
105005, Москва, МГТУ им.Н.Э.Баумана, кафедра РК-6 (САПР),
https://rk6.bmstu.ru/index.php?option=com_content&view=article&id=44&catid=10&Itemid=128
<http://www.bmstu.ru/ps/~manichev/>





<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

чт, 6 янв. 2022 г. в 22:44, Evgeny Shtanov ***@***.***>:
